version: 2.1

orbs:
  win: circleci/windows@2.2.0
  rsync: germade/rsync@0.0.1

jobs:
  test:
    description: Do some example testing first
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - run:
          name: "Run app tests"
          command: dotnet.exe test
  build:
    description: Build app with Release configurations
    executor: win/default

    steps:
      - checkout
      - run: dotnet build --configuration Release
        
  deploy:
    description: Deploy app to vm
    executor: win/default
    
    steps:
      - checkout
      - run: rsync -avz -e 'ssh' bin/Release/netcoreapp3.1/publish/ 45.76.124.226@root:/home/deploy/apps/BlazorExampleApp
      - run: ssh 45.76.124.226@root "sudo supervisorctl restart web-myapp"

workflows:
  test_and_build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
            - build