version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  test:
    description: Do some example testing first
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - run:
          name: "Run app tests"
          command: dotnet.exe test
  build:
    description: Build app with Release configurations
    executor: win/default

    steps:
      - checkout
      - run: dotnet build --configuration Release

workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
