version: 2.1

jobs:
  test:
    description: Do some example testing first
    docker:
      - image: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet restore
      - run:
          name: "Run app tests"
          command: dotnet test
  build:
    description: Build app with Release configurations
    docker:
      - image: 'mcr.microsoft.com/dotnet/core/sdk:3.1'

    steps:
      - checkout
      - run: dotnet build --configuration Release
        
  deploy:
    description: Deploy app to vm
    machine:
      image: 'ubuntu-1604:201903-01'
    
    steps:
      - checkout
      - deploy:
          name: Rsync app
          command: rsync -avzhe 'ssh' --progress bin/Release/netcoreapp3.1/publish/ $SSH_USER@$SSH_HOST:/home/deploy/apps/BlazorExampleApp
      - deploy:
          name: Restart suervisorclt
          command: ssh $SSH_USER@$SSH_HOST "sudo supervisorctl restart web-BlazorExampleApp"

workflows:
  test_and_build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master # only deploy on the master branch
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master # only deploy on the master branch