version: 2.1

jobs:
  test:
    description: Do some example testing first
    docker:
      - image: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet restore
      - run:
          name: "Run app tests"
          command: dotnet test
  build:
    description: Build app with Release configurations
    machine:
      image: 'ubuntu-1604:201903-01'

    steps:
      - add_ssh_keys:
          fingerprints:
            - "e6:e5:95:83:44:23:4f:d8:9d:40:2e:d0:d8:54:a0:4f"
      - checkout
      - run:
          name: Add package signing key
          command: |
            wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
      - run:
          name: Install dotnet core 3.1
          command: |
            sudo apt-get update; 
            sudo apt-get install -y apt-transport-https && \
            sudo apt-get update && \
            sudo apt-get install -y dotnet-sdk-3.1
      - run:
          name: Install project dependencies
          command: dotnet restore
      - run: dotnet build --configuration Release
      - run:
          name: Test ssh connection
          command: ssh $SSH_USER@$SSH_HOST "echo deploying..."
      - run:
          name: Rsync app
          command: rsync -avzhe ssh --progress ~/bin/Release/netcoreapp3.1/ $SSH_USER@$SSH_HOST:/home/deploy/apps/BlazorExampleApp
      - run:
          name: Restart supervisorclt
          command: ssh $SSH_USER@$SSH_HOST "sudo supervisorctl restart web-BlazorExampleApp"

workflows:
  test_and_build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master # only deploy on the master branch