version: 2.1

jobs:
  test:
    description: Do some example testing first
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - run:
          name: "Run app tests"
          command: dotnet.exe test
  build:
    description: Build app with Release configurations
    machine:
      image: 'ubuntu-1604:201903-01'

    steps:
      - checkout
      - run: dotnet build --configuration Release
        
  deploy:
    description: Deploy app to vm
    machine:
      image: 'ubuntu-1604:201903-01'
    
    steps:
      - checkout
      - deploy:
          name: Rsync app
          command: rsync -avz -e 'ssh' bin/Release/netcoreapp3.1/publish/ 45.76.124.226@root:/home/deploy/apps/BlazorExampleApp
      - deploy:
          name: Restart suervisorclt
          command: ssh 45.76.124.226@root "sudo supervisorctl restart web-BlazorExampleApp"

workflows:
  test_and_build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
            - build